Repository DataBiosphere/terra-ui, pull requests merged in 2019-05, with the labels that each got.

#1531 fix data selection in read-only mode
  src/pages/workspaces/workspace/Data.js
Labels: risk: low

#1498 IGV in Terra
  package-lock.json
  package.json
  src/components/IGVBrowser.js
  src/components/IGVFileSelector.js
  src/pages/workspaces/workspace/Data.js
Labels: needs product

#1535 Update documentation links
  src/components/FreeTrialEulas.js
  src/components/NewWorkspaceModal.js
  src/components/TrialBanner.js
  src/pages/SignIn.js
  src/pages/TermsOfService.js
  src/pages/billing/List.js
  src/pages/workspaces/workspace/Tools.js
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1532 tweak workspace sharing UI
  src/libs/utils.js
  src/pages/workspaces/List.js
  src/pages/workspaces/workspace/ShareWorkspaceModal.js
  src/pages/workspaces/workspace/WorkspaceContainer.js
Labels: risk: low

#1543 make routes more data-centric
  src/components/Router.js
  src/libs/nav.js
  src/pages/ImportData.js
  src/pages/ImportTool.js
  src/pages/LandingPage.js
  src/pages/PrivacyPolicy.js
  src/pages/Profile.js
  src/pages/StyleGuide.js
  src/pages/TermsOfService.js
  src/pages/billing/List.js
  src/pages/groups/Group.js
  src/pages/groups/List.js
  src/pages/library/Code.js
  src/pages/library/DataExplorer.js
  src/pages/library/Datasets.js
  src/pages/library/Showcase.js
  src/pages/workspaces/List.js
  src/pages/workspaces/workspace/Dashboard.js
  src/pages/workspaces/workspace/Data.js
  src/pages/workspaces/workspace/JobHistory.js
  src/pages/workspaces/workspace/Notebooks.js
  src/pages/workspaces/workspace/Tools.js
  src/pages/workspaces/workspace/jobHistory/SubmissionDetails.js
  src/pages/workspaces/workspace/notebooks/NotebookLauncher.js
  src/pages/workspaces/workspace/notebooks/TerminalLauncher.js
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1547 Remove gtex
  src/images/library/datasets/GTeX@2x.png
  src/pages/library/Datasets.js
Labels: risk: low

#1555 fix output defaults on incomplete workflow configs
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1542 formalize common search components
  src/components/DataTable.js
  src/components/common.js
  src/components/input.js
  src/pages/StyleGuide.js
  src/pages/groups/Group.js
  src/pages/groups/List.js
  src/pages/workspaces/List.js
  src/pages/workspaces/workspace/Data.js
  src/pages/workspaces/workspace/JobHistory.js
  src/pages/workspaces/workspace/jobHistory/SubmissionDetails.js
Labels: risk: low

#1559 misc data table improvements
  src/components/DataTable.js
  src/components/table.js
  src/libs/data-utils.js
Labels: risk: low

#1561 fix focus error on autocomplete
  src/components/input.js
Labels: risk: low

#1563 handle potential overflow on job history
  src/pages/workspaces/workspace/JobHistory.js
Labels: risk: low

#1552 Terra alerts notifications
  src/components/Router.js
  src/components/ServiceAlerts.js
  src/libs/ajax.js
  src/libs/utils.js
  src/pages/Main.js
Labels: risk: low

#1574 updates to branding and landing page
  src/components/FooterWrapper.js
  src/components/NpsSurvey.js
  src/components/Router.js
  src/components/TrialBanner.js
  src/components/icons.js
  src/icons/arrow-right.svg
  src/images/landing-page-hero.jpg
  src/images/landing-page-hero.png
  src/images/text-frame.svg
  src/libs/auth.js
  src/libs/data-utils.js
  src/libs/logos.js
  src/libs/style.js
  src/pages/LandingPage.js
  src/pages/SignIn.js
  src/pages/library/Code.js
  src/pages/library/Datasets.js
Labels: Noteworthy!

#1539 show ws tabs when editing tool
  src/pages/workspaces/workspace/notebooks/NotebookLauncher.js
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: Noteworthy!

#1582 fix early getConfig call
  src/components/TrialBanner.js
Labels: risk: low

#1585 fix AutocompleteTextInput
  src/components/input.js
Labels: risk: low

#1592 remove localize retry from notebook launcher
  src/pages/workspaces/workspace/notebooks/NotebookLauncher.js
Labels: risk: low

#1584 open links from notebook previews in a new tab
  src/libs/utils.js
  src/pages/workspaces/workspace/notebooks/NotebookLauncher.js
Labels: risk: low

#1556 New Workspace modal update for users without a billing project
  src/components/FreeCreditsModal.js
  src/components/NewWorkspaceModal.js
  src/components/TopBar.js
  src/components/TrialBanner.js
  src/pages/Main.js
Labels: risk: low

#1596 create syncAtomToSessionStorage helper
  src/components/CardsListToggle.js
  src/libs/config.js
  src/libs/utils.js
Labels: risk: low

#1587 reconcile inputs and outputs when switching method versions
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1600 standardize ajax calls
  src/libs/ajax.js
  src/libs/auth.js
Labels: risk: low

#1611 hide job manager link if workflow id is missing
  src/pages/workspaces/workspace/jobHistory/SubmissionDetails.js
Labels: risk: low

#1615 improve ajax override framework
  src/libs/ajax.js
Labels: risk: low

#1613 Add mailto link if support request fails
  src/components/SupportRequest.js
Labels: risk: low

#1620 warn about changes to circle secret handling code
  .hooks/pre-commit
Labels: risk: low

#1631 centralize global app state
  src/components/AuthContainer.js
  src/components/CardsListToggle.js
  src/components/ConfigOverridesWarning.js
  src/components/FreeCreditsModal.js
  src/components/NewWorkspaceModal.js
  src/components/Notifications.js
  src/components/NpsSurvey.js
  src/components/SupportRequest.js
  src/components/TopBar.js
  src/components/TrialBanner.js
  src/components/workspace-utils.js
  src/libs/ajax.js
  src/libs/auth.js
  src/libs/config.js
  src/libs/state.js
  src/pages/Profile.js
  src/pages/Register.js
  src/pages/TermsOfService.js
  src/pages/billing/NewAccountModal.js
  src/pages/workspaces/workspace/WorkspaceContainer.js
  src/pages/workspaces/workspace/tools/FailureRerunner.js
Labels: risk: low

#1632 refactor notebook launcher page
  src/components/ClusterManager.js
  src/libs/utils.js
  src/pages/workspaces/workspace/WorkspaceContainer.js
  src/pages/workspaces/workspace/notebooks/NotebookLauncher.js
Labels: risk: low

#1571 Allow users to see output of a failed userscript (don't merge until Leo side of ticket is merged!)
  config/fiab.json
  src/components/ClusterManager.js
  src/components/UriViewer.js
  src/libs/ajax.js
  src/libs/state.js
  src/libs/utils.js
  src/pages/workspaces/workspace/WorkspaceContainer.js
Labels: on hold

#1382 Drop default disk size down to 50GB
  src/components/ClusterManager.js
  src/libs/utils.js
Labels: risk: low

#1667 move "filter by"
  src/pages/workspaces/List.js
Labels: risk: low

#1669 improve error text when previewing file [SATURN-41]
  src/components/UriViewer.js
Labels: risk: low
