Repository DataBiosphere/terra-ui, pull requests merged in 2019-04, with the labels that each got.

#1309 billing account creation modal
  src/components/Modal.js
  src/components/common.js
  src/components/icons.js
  src/components/workspace-utils.js
  src/icons/credit-card.svg
  src/icons/purchase-order.svg
  src/libs/style.js
  src/libs/utils.js
  src/pages/Profile.js
  src/pages/billing/List.js
  src/pages/billing/NewAccountModal.js
  src/pages/workspaces/workspace/Notebooks.js
Labels: Blocked

#1365 block non-public pages until profile is loaded
  src/components/AuthContainer.js
Labels: risk: low

#1364 move workspace list from sessionStorage to memory
  src/components/workspace-utils.js
  src/pages/library/Showcase.js
  src/pages/workspaces/List.js
Labels: risk: low

#1359 refactor workspace wrapper
  src/pages/workspaces/workspace/WorkspaceContainer.js
Labels: risk: low

#1375 allow explicit setting of canCompute and canShare flags
  src/components/common.js
  src/pages/workspaces/workspace/ShareWorkspaceModal.js
Labels: risk: low

#1402 show workspace dataset attributes on dashboard
  src/components/table.js
  src/data/workspace-attributes.js
  src/libs/ajax.js
  src/pages/workspaces/workspace/Dashboard.js
Labels: risk: low

#1409 allow disabling call caching
  src/components/StepButtons.js
  src/pages/workspaces/workspace/tools/LaunchAnalysisModal.js
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1407 add entity name to submissions table
  src/pages/workspaces/workspace/JobHistory.js
Labels: risk: low

#1410 use correct sharing permissions
  src/pages/workspaces/List.js
  src/pages/workspaces/workspace/WorkspaceContainer.js
Labels: risk: low

#1413 reduce workspace loads when switching tabs
  src/pages/workspaces/workspace/WorkspaceContainer.js
Labels: risk: low

#1417 make logos into components
  src/components/FooterWrapper.js
  src/components/TopBar.js
  src/components/common.js
  src/libs/logos.js
  src/pages/ImportData.js
  src/pages/Register.js
  src/pages/SignIn.js
  src/pages/TermsOfService.js
Labels: risk: low

#1420 delay app rendering until config is loaded
  src/index.js
Labels: risk: low

#1433 add firecloud as a return value
  src/components/common.js
  src/libs/logos.js
  src/pages/library/Code.js
  src/pages/library/Datasets.js
Labels: risk: low

#1437 convert library content into components
  src/pages/library/Datasets.js
Labels: risk: low

#1436 prevent UI actions when workspace is locked
  src/libs/utils.js
  src/pages/workspaces/workspace/Dashboard.js
  src/pages/workspaces/workspace/Data.js
  src/pages/workspaces/workspace/Tools.js
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1450 save preferences separately from profile
  src/libs/ajax.js
  src/pages/Profile.js
Labels: risk: low

#1453 enable upload and download of workspace attributes
  src/libs/ajax.js
  src/pages/workspaces/workspace/Data.js
Labels: risk: low

#1465 remove data entities from state history
  src/components/DataTable.js
Labels: risk: low

#1468 fix workflow inputs upload
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1470 fix spinner z-index
  src/components/common.js
  src/libs/style.js
  src/pages/billing/List.js
Labels: risk: low

#1471 clear billing project if inaccessible when cloning
  src/components/NewWorkspaceModal.js
Labels: risk: low

#1472 make preview error text wrap better
  src/components/UriViewer.js
Labels: risk: low

#1487 Add workspace name to delete confirmation
  src/pages/workspaces/workspace/DeleteWorkspaceModal.js
Labels: risk: low

#1494 autosuggest id column in workflow config
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: risk: low

#1467 Go back to fc modal
  src/components/TopBar.js
  src/libs/ajax.js
Labels: risk: low

#1497 fix job views when no inputs/entities
  src/pages/workspaces/workspace/JobHistory.js
  src/pages/workspaces/workspace/jobHistory/SubmissionDetails.js
Labels: risk: low

#1455 Toast message when user is redirected
  src/components/Notifications.js
  src/components/Router.js
  src/components/common.js
Labels: risk: low

#1501 improve TextArea api
  src/components/NewWorkspaceModal.js
  src/components/NpsSurvey.js
  src/components/SupportRequest.js
  src/components/TopBar.js
  src/components/input.js
Labels: risk: low

#1495 handle no-access workspaces better
  src/pages/workspaces/List.js
Labels: risk: low

#1499 change snapshot of tool when redacted
  src/pages/workspaces/workspace/Tools.js
  src/pages/workspaces/workspace/tools/WorkflowView.js
Labels: FireCloud-feature-gap

#1489 update dockstore api url by request
  src/libs/ajax.js
Labels: risk: low

#1506 show submission status on workspace list
  src/pages/workspaces/List.js
Labels: risk: low

#1504 add submitted icon
  src/components/job-common.js
  src/pages/workspaces/workspace/JobHistory.js
  src/pages/workspaces/workspace/jobHistory/SubmissionDetails.js
Labels: risk: low

#1514 clean up isFirecloud code
  src/components/TopBar.js
  src/components/common.js
  src/libs/config.js
  src/libs/logos.js
  src/pages/library/Code.js
  src/pages/library/Datasets.js
Labels: risk: low

#1518 only show fully created billing projects in new workspace modal
  src/components/NewWorkspaceModal.js
Labels: risk: low

#1520 delay NIH status check until user is registered
  src/libs/auth.js
Labels: risk: low

#1500 Remove JupyterLab launch buttons
  src/pages/workspaces/workspace/Notebooks.js
  src/pages/workspaces/workspace/notebooks/NotebookLauncher.js
Labels: needs product, risk: low

#1515 filter workspaces by submission status
  src/pages/workspaces/List.js
Labels: risk: low

#1517 Search workspace tags
  src/libs/ajax.js
  src/pages/workspaces/List.js
Labels: risk: low

#1415 Remove tide and whitelist
  src/components/AuthContainer.js
  src/data/prod-whitelist.js
  src/libs/auth.js
  src/pages/Disabled.js
Labels: on hold, risk: low

#1509 Clarify UKBB Data Explorer only for Kathiresan Lab
  src/pages/library/Datasets.js
Labels: needs product
