Repository DataBiosphere/terra-ui, pull requests merged in 2020-05, with the labels that each got.

#2143 handle rp with igv [SATURN-1613]
  src/components/IGVBrowser.js
  src/components/UriViewer.js
  src/components/workspace-utils.js
  src/libs/ajax.js
  src/libs/data-utils.js
  src/libs/state.js
  src/pages/workspaces/workspace/Data.js
Labels: Working on PR Feedback

#2137 Add notifications for framework service expirations [SATURN-1372]
  src/components/common.js
  src/libs/auth.js
  src/pages/Profile.js
Labels: Working on PR Feedback

#2142 Add a dynamic favicon for bdc [SATURN-1587]
  package.json
  src/components/Favicon.js
  src/images/brands/bioDataCatalyst/bioDataCatalyst-favicon.jpg
  src/pages/Main.js
  yarn.lock
Labels: Please Review!

#2138 Allow creating sets of sets and launching in a single submission [SATURN-1321]
  src/pages/workspaces/workspace/Data.js
  src/pages/workspaces/workspace/workflows/DataStepContent.js
  src/pages/workspaces/workspace/workflows/LaunchAnalysisModal.js
  src/pages/workspaces/workspace/workflows/WorkflowView.js
Labels: Please Review!

#2147 Add workflow source and snapshotId [SATURN-1621]
  src/libs/events.js
  src/pages/workspaces/workspace/JobHistory.js
  src/pages/workspaces/workspace/workflows/FailureRerunner.js
  src/pages/workspaces/workspace/workflows/WorkflowView.js
Labels: Please Review!

#2148 Add workspace details to metric events [SATURN-1624]
  src/libs/events.js
  src/pages/ImportData.js
  src/pages/ImportWorkflow.js
  src/pages/workspaces/workspace/ShareWorkspaceModal.js
  src/pages/workspaces/workspace/Workflows.js
  src/pages/workspaces/workspace/workflows/FailureRerunner.js
  src/pages/workspaces/workspace/workflows/WorkflowView.js
Labels: Please Review!

#2146 remediate terms of service [SATURN-1609]
  src/pages/TermsOfService.js
  src/style.css
Labels: Please Review!, help wanted
